name: Mac
on:
  push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install packages with Homebrew
        run: |
          brew update
          brew install qt libgcrypt libsodium argon2
          brew link qt
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
#          ref: mac-el-capitan
      - name: Build
        run: |
          cmake \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \
            -DWITH_XC_ALL=OFF \
            -DWITH_XC_UPDATECHECK=OFF \
            -DWITH_TESTS=OFF \
            -DWITH_APP_BUNDLE=OFF \
            -DKEEPASSXC_BUILD_TYPE=Release
          make -j cli