name: Mac
on:
  push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \
            -DWITH_XC_ALL=OFF \
            -DWITH_XC_UPDATECHECK=OFF \
            -DWITH_TESTS=OFF \
            -DWITH_APP_BUNDLE=OFF \
            -DKEEPASSXC_BUILD_TYPE=Release
          make -j cli